### ISSUE TITLE
Differential Drive Plugin

### ISSUE THREAD

**Issue by Shobuj-Paul** [IEEE-NITK/SLAMBot#11]
## Use case

To control the robot in Gazebo using keyboard bindings, we need to set up `/cmd_vel` topic which connects to the wheel controllers using a differential drive setup.

## Proposal

Use the [differential drive plugin](https://classic.gazebosim.org/tutorials?tut=ros_gzplugins#DifferentialDrive) as given in Gazebo documentation and edit the given parameters in the _slambot_plugins.gazebo_ file given [here](https://github.com/IEEE-NITK/SLAMBot/blob/differential_drive_plugin/slambot_description/gazebo/slambot_plugins.gazebo). Get the robot's physical parameters from the CAD model in Fusion360.

**Comment by Shivani-Chanda** [comment]
differential drive plugin updated with the correct physical parameters.
