### ISSUE TITLE
Embedded code for rosserial communication

### ISSUE THREAD

**Issue by Shobuj-Paul** [IEEE-NITK/SLAMBot#14]
## Description

The Arduino side rosserial codes do not connect to any hardware actions yet. Functions for calculating odometry, transform, etc. need to be completed and stored in their respective message types for proper publisher-subscriber relations.

## Steps to Reproduce

Open the [_differential_drive.ino_](https://github.com/IEEE-NITK/SLAMBot/blob/rosserial/slambot_arduino/differential_drive/differential_drive.ino) code in Arduino IDE. Upload it to your Arduino Mega board after setting the port and board parameters.
Run the rosserial node after running `roscore`:
```bash
rosrun rosserial_arduino serial_node.py
```
Running `rostopic list` gives you a bunch of topics on your Linux PC, but the contents of these topics are blank (check `rostopic echo`). Do the necessary calculations and complete the Arduino functions. Complete the `void loop()` part of the code.

### Expected Results

Sensor readings from Encoders, IMU, etc., should be published accurately on the computer. Motors should correctly respond to `/cmd_vel` command given on the computer.

### Actual results

Blank topics, no response from `/cmd_vel`.

### ROS Configuration

Which ROS Version are you using?

- [x] Noetic
- [ ] Melodic
- [ ] Foxy
- [ ] Humble
- [ ] Rolling

### Operating System

Which OS are you using?

- [ ] Windows
- [ ] MacOS
- [x] Ubuntu Linux (Mention Version) 20.04
- [ ] Other Linux (Mention Below)

**Comment by Shobuj-Paul** [comment]
The Arduino code can be structured like the Atmega328P-based OpenCR board like [this](https://github.com/ROBOTIS-GIT/OpenCR/tree/master/arduino/opencr_arduino/opencr/libraries/turtlebot3/examples/turtlebot3_burger).

**Comment by SpandanPatkar** [comment]
@Shobuj-Paul I have Updated the Arduino Codes, please have a look at it once.

**Comment by Shobuj-Paul** [comment]
Has hardware testing been done? If yes, then you can open a pull request.

**Comment by Shobuj-Paul** [comment]
@SpandanPatkar Open a PR after confirming hardware testing and mention exactly the hardware tests conducted in the PR.
