### ISSUE TITLE
LIDAR Plugin

### ISSUE THREAD

**Issue by Shobuj-Paul** [IEEE-NITK/SLAMBot#17]
## Use case

A plugin for LIDAR needs to be added for range sensing and mapping.

## Proposal

Add the appropriate Gazebo plugin from their [page](https://classic.gazebosim.org/tutorials?tut=ros_gzplugins) in the _slambot_plugins.gazebo_ file.
Enable visualization in Gazebo. Keep the range as 6m, as that will be the range of our RPLidar.

**Comment by Shivani-Chanda** [comment]
LIDAR plugin added with max range 6m, visualization enabled.

**Comment by Shobuj-Paul** [comment]
Only normal "ray" should be used instead of "gpu_ray" because, for some reason, "gpu_ray" doesn't seem to give either proper visualization or work with Rviz.
Have fixed the issue in https://github.com/IEEE-NITK/SLAMBot/commit/9ad8e5f83634bb7824211e6ea094e0d7829cf498. 
Have also changed the minimum range to _0.10_ since the robot body was interfering with the laser.

**Comment by Shobuj-Paul** [comment]
Pull request can be opened for _lidar-plugin_ branch.
